c0: C_test_cv.cxx
	g++ `pkg-config opencv --cflags --libs` $^ -o $@
c2: C2_test_cv.cxx
	g++ `pkg-config opencv --cflags --libs` $^ -o $@
c3: C3_test_cv.cxx
	g++ `pkg-config opencv --cflags --libs` $^ -o $@
c4: C4_test_cv.cxx
	g++ `pkg-config opencv --cflags --libs` $^ -o $@
